name: flutter_rx_core
description: The core library used by flutter_rx
repository: https://github.com/Jordan-Nelson/flutter_rx
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  memoize: ^3.0.0
  meta: ^1.7.0
  rxdart: ^0.27.0

dev_dependencies:
  lints: ^2.0.0
