name: flutter_rx
description: A redux style state management library, loosely inspired by NgRx.
repository: https://github.com/Jordan-Nelson/flutter_rx
version: 0.5.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rx_core: ^0.1.0
  rxdart: ^0.27.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
