# Created with package:mono_repo v6.2.2
name: Dart Lint
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.2.2
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze; Dart dev; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos lib test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:packages/flutter_rx_core;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:packages/flutter_rx_core
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v3
      - id: packages_flutter_rx_core_pub_upgrade
        name: packages/flutter_rx_core; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/flutter_rx_core
        run: dart pub upgrade
      - name: "packages/flutter_rx_core; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_flutter_rx_core_pub_upgrade.conclusion == 'success'"
        working-directory: packages/flutter_rx_core
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/flutter_rx_core; dart analyze --fatal-infos lib test"
        if: "always() && steps.packages_flutter_rx_core_pub_upgrade.conclusion == 'success'"
        working-directory: packages/flutter_rx_core
        run: dart analyze --fatal-infos lib test
  job_003:
    name: "analyze; Dart stable; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos lib test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/flutter_rx_core;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/flutter_rx_core
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3
      - id: packages_flutter_rx_core_pub_upgrade
        name: packages/flutter_rx_core; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/flutter_rx_core
        run: dart pub upgrade
      - name: "packages/flutter_rx_core; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_flutter_rx_core_pub_upgrade.conclusion == 'success'"
        working-directory: packages/flutter_rx_core
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/flutter_rx_core; dart analyze --fatal-infos lib test"
        if: "always() && steps.packages_flutter_rx_core_pub_upgrade.conclusion == 'success'"
        working-directory: packages/flutter_rx_core
        run: dart analyze --fatal-infos lib test
